[tools]
act = "0.2.88"
grype = "0.112.0"
golangci-lint = "2.12.2"
golangci-lint-langserver = "0.0.12"
go = "1.26.3"
"go:golang.org/x/tools/gopls" = "0.22.0"
"go:github.com/loov/goda" = "0.9.3"
pinact = "3.10.1"

[settings]
lockfile = true
experimental = true
