//go:build ignore

package main

import (
	"flag"
	"fmt"
	"io"
	"os"
)

const (
	licPrefix = `// NOTE: Code generated by go generate; DO NOT EDIT.

package main

import (
	"os"
)

func printLicense() {
	_, _ = os.Stdout.WriteString(license)
	os.Exit(0)
}

const license = `

	licPostfix = `
`
)

func main() {

	inFile := flag.String("in", "", "input file")
	outFile := flag.String("out", "", "output file")
	flag.Parse()

	inReader, outWriter := os.Stdin, os.Stdout
	err := error(nil)

	if *inFile != "" {
		if inReader, err = os.Open(*inFile); err != nil {
			fmt.Fprintf(os.Stderr, "error: reading -in %q: %s\n", *inFile, err)
			os.Exit(13)
		}
	}
	if *outFile != "" {
		if outWriter, err = os.Create(*outFile); err != nil {
			fmt.Fprintf(os.Stderr, "error: writing -out %q: %s\n", *outFile, err)
			os.Exit(13)
		}
	}

	fmt.Fprint(outWriter, licPrefix)
	fmt.Fprint(outWriter, "`")
	io.Copy(outWriter, inReader)
	fmt.Fprint(outWriter, "`")
	fmt.Fprint(outWriter, licPostfix)
}
